import { clsx, type ClassValue } from "clsx"
import { twMerge } from "tailwind-merge"

/** Generated by ui.shadcn for use with tailwindcss */
export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs))
}
