//
// I WOULDN'T NORMALLY HAVE A
//

import { constuctAPIEndpoint } from "../constants";

export interface User {
  id: number;
  email: string;
  firstName: string;
  lastName: string;
  managerId?: number;
  photo: string;
}

export interface DbUser extends User {
  password: string;
}

/**
 * Gets All Users. All users are pulled from the database defined at API_URL
 */
export async function getAllUsers(): Promise<User[]> {
  const users = await fetch(constuctAPIEndpoint("users")).then((res) =>
    res.json()
  );
  const passwordlessUsers = users.map(({ password, ...rest }: DbUser) => rest);
  return passwordlessUsers;
}

/**
 * Gets A Single User. Uses the secret generated from the Gong encode function and fetches it from the database
 * @param secret - The 'secret' generated by the Gong encode function
 */
export async function getUserBySecret(secret: string): Promise<User | null> {
  // VERIFY USER EXISTS
  const singleUserId = await fetch(
    constuctAPIEndpoint(`secrets/${secret}`)
  ).then((res) => res.json());
  console.log(singleUserId);
  if (!singleUserId) {
    return null;
  }
  // GET ALL USERS
  const allUsers = await getAllUsers();
  const singleUser = allUsers.filter((a) => a.id === singleUserId);
  // NO USER FOUND WITH ID
  if (singleUser.length == 0) {
    return null;
  }
  // ASSUMES THAT THERE IS ONLY 1 USER ID, AND IT IS UNIQUE
  return singleUser[0];
}
